@startuml 

hide circle
hide method
hide attribute
left to right direction

package View {
    class MainWindow
    class SubTeacherWindow
    class CreateSubTeacherWindow
}

package ViewModel {
    class MainViewModel
    class SubTeacherViewModel

}

package Model {
    class SubTeacher

}


View -> ViewModel
ViewModel -> View
ViewModel -> Model
 MainViewModel -> SubTeacherViewModel
 SubTeacherViewModel -> SubTeacher
 SubTeacherWindow -> SubTeacherViewModel
 CreateSubTeacherWindow -> SubTeacherViewModel


@enduml